touch ./postgresql/base/.gitkeep
touch ./postgresql/base/1/.gitkeep
touch ./postgresql/base/13756/.gitkeep
touch ./postgresql/base/13757/.gitkeep
touch ./postgresql/base/16384/.gitkeep
touch ./postgresql/global/.gitkeep
touch ./postgresql/pg_commit_ts/.gitkeep
touch ./postgresql/pg_dynshmem/.gitkeep
touch ./postgresql/pg_logical/.gitkeep
touch ./postgresql/pg_logical/mappings/.gitkeep
touch ./postgresql/pg_logical/snapshots/.gitkeep
touch ./postgresql/pg_multixact/.gitkeep
touch ./postgresql/pg_multixact/members/.gitkeep
touch ./postgresql/pg_multixact/offsets/.gitkeep
touch ./postgresql/pg_notify/.gitkeep
touch ./postgresql/pg_replslot/.gitkeep
touch ./postgresql/pg_serial/.gitkeep
touch ./postgresql/pg_snapshots/.gitkeep
touch ./postgresql/pg_stat/.gitkeep
touch ./postgresql/pg_stat_tmp/.gitkeep
touch ./postgresql/pg_subtrans/.gitkeep
touch ./postgresql/pg_tblspc/.gitkeep
touch ./postgresql/pg_twophase/.gitkeep
touch ./postgresql/pg_wal/.gitkeep
touch ./postgresql/pg_wal/archive_status/.gitkeep
touch ./postgresql/pg_xact/.gitkeep