touch ./base/.gitkeep
touch ./base/1/.gitkeep
touch ./base/13756/.gitkeep
touch ./base/13757/.gitkeep
touch ./base/16384/.gitkeep
touch ./global/.gitkeep
touch ./pg_commit_ts/.gitkeep
touch ./pg_dynshmem/.gitkeep
touch ./pg_logical/.gitkeep
touch ./pg_logical/mappings/.gitkeep
touch ./pg_logical/snapshots/.gitkeep
touch ./pg_multixact/.gitkeep
touch ./pg_multixact/members/.gitkeep
touch ./pg_multixact/offsets/.gitkeep
touch ./pg_notify/.gitkeep
touch ./pg_replslot/.gitkeep
touch ./pg_serial/.gitkeep
touch ./pg_snapshots/.gitkeep
touch ./pg_stat/.gitkeep
touch ./pg_stat_tmp/.gitkeep
touch ./pg_subtrans/.gitkeep
touch ./pg_tblspc/.gitkeep
touch ./pg_twophase/.gitkeep
touch ./pg_wal/.gitkeep
touch ./pg_wal/archive_status/.gitkeep
touch ./pg_xact/.gitkeep